FIRST_NAME_DATA = (
    ("Aaron", "m"),
    ("Abigail", "f"),
    ("Adam", "m"),
    ("Adrian", "m"),
    ("Aidan", "m"),
    ("Alan", "m"),
    ("Albert", "m"),
    ("Alex", "m"),
    ("Alexa", "f"),
    ("Alfred", "m"),
    ("Alice", "f"),
    ("Allison", "f"),
    ("Amber", "f"),
    ("Amelia", "f"),
    ("Amy", "f"),
    ("Andrea", "f"),
    ("Andrew", "m"),
    ("Angela", "f"),
    ("Anna", "f"),
    ("Annie", "f"),
    ("Anthony", "m"),
    ("April", "f"),
    ("Arthur", "m"),
    ("Ashley", "f"),
    ("Audrey", "f"),
    ("Austin", "m"),
    ("Ava", "f"),
    ("Avery", "f"),
    ("Barbara", "f"),
    ("Beatrice", "f"),
    ("Bella", "f"),
    ("Benjamin", "m"),
    ("Beth", "f"),
    ("Beverly", "f"),
    ("Blake", "m"),
    ("Bradley", "m"),
    ("Brandon", "m"),
    ("Brenda", "f"),
    ("Brian", "m"),
    ("Brianna", "f"),
    ("Brooke", "f"),
    ("Bruce", "m"),
    ("Bryce", "m"),
    ("Caleb", "m"),
    ("Calvin", "m"),
    ("Cameron", "m"),
    ("Carl", "m"),
    ("Carol", "f"),
    ("Caroline", "f"),
    ("Carrie", "f"),
    ("Casey", "f"),
    ("Cassandra", "f"),
    ("Catherine", "f"),
    ("Cecilia", "f"),
    ("Charles", "m"),
    ("Charlotte", "f"),
    ("Cheryl", "f"),
    ("Chloe", "f"),
    ("Christian", "m"),
    ("Christina", "f"),
    ("Claire", "f"),
    ("Clara", "f"),
    ("Clarence", "m"),
    ("Cody", "m"),
    ("Cole", "m"),
    ("Colin", "m"),
    ("Colton", "m"),
    ("Connor", "m"),
    ("Cooper", "m"),
    ("Courtney", "f"),
    ("Curtis", "m"),
    ("Daisy", "f"),
    ("Dana", "f"),
    ("Daniel", "m"),
    ("Darren", "m"),
    ("David", "m"),
    ("Deborah", "f"),
    ("Denise", "f"),
    ("Dennis", "m"),
    ("Derek", "m"),
    ("Diana", "f"),
    ("Dominic", "m"),
    ("Donald", "m"),
    ("Donna", "f"),
    ("Dorothy", "f"),
    ("Dylan", "m"),
    ("Edith", "f"),
    ("Edmund", "m"),
    ("Edward", "m"),
    ("Elaine", "f"),
    ("Eleanor", "f"),
    ("Eli", "m"),
    ("Elijah", "m"),
    ("Elizabeth", "f"),
    ("Ella", "f"),
    ("Elliot", "m"),
    ("Emily", "f"),
    ("Emma", "f"),
    ("Eric", "m"),
    ("Erin", "f"),
    ("Ethan", "m"),
    ("Eva", "f"),
    ("Evelyn", "f"),
    ("Felix", "m"),
    ("Fiona", "f"),
    ("Florence", "f"),
    ("Frank", "m"),
    ("Frederick", "m"),
    ("Gabriel", "m"),
    ("Gavin", "m"),
    ("George", "m"),
    ("Georgia", "f"),
    ("Gerald", "m"),
    ("Gillian", "f"),
    ("Gloria", "f"),
    ("Grace", "f"),
    ("Graham", "m"),
    ("Gregory", "m"),
    ("Hailey", "f"),
    ("Hannah", "f"),
    ("Harper", "f"),
    ("Harriet", "f"),
    ("Harrison", "m"),
    ("Hazel", "f"),
    ("Heather", "f"),
    ("Henry", "m"),
    ("Holly", "f"),
    ("Howard", "m"),
    ("Ian", "m"),
    ("Irene", "f"),
    ("Isaac", "m"),
    ("Isabella", "f"),
    ("Ivy", "f"),
    ("Jack", "m"),
    ("Jacob", "m"),
    ("James", "m"),
    ("Jamie", "f"),
    ("Janet", "f"),
    ("Jared", "m"),
    ("Jasmine", "f"),
    ("Jeffrey", "m"),
    ("Jenna", "f"),
    ("Jennifer", "f"),
    ("Jeremy", "m"),
    ("Jessica", "f"),
    ("Joanna", "f"),
    ("Joel", "m"),
    ("John", "m"),
    ("Jonathan", "m"),
    ("Jordan", "m"),
    ("Joseph", "m"),
    ("Joshua", "m"),
    ("Jude", "m"),
    ("Julia", "f"),
    ("Julian", "m"),
    ("Justin", "m"),
    ("Karen", "f"),
    ("Kate", "f"),
    ("Katherine", "f"),
    ("Kathleen", "f"),
    ("Kayla", "f"),
    ("Keith", "m"),
    ("Kevin", "m"),
    ("Kristen", "f"),
    ("Kyle", "m"),
    ("Laura", "f"),
    ("Lauren", "f"),
    ("Leah", "f"),
    ("Leo", "m"),
    ("Leonard", "m"),
    ("Leslie", "f"),
    ("Liam", "m"),
    ("Lily", "f"),
    ("Linda", "f"),
    ("Logan", "m"),
    ("Lorraine", "f"),
    ("Louis", "m"),
    ("Lucas", "m"),
    ("Lucy", "f"),
    ("Luke", "m"),
    ("Lydia", "f"),
    ("Mackenzie", "f"),
    ("Madison", "f"),
    ("Malcolm", "m"),
    ("Marcus", "m"),
    ("Margaret", "f"),
    ("Maria", "f"),
    ("Marissa", "f"),
    ("Mark", "m"),
    ("Martin", "m"),
    ("Marvin", "m"),
    ("Mason", "m"),
    ("Matthew", "m"),
    ("Max", "m"),
    ("Megan", "f"),
    ("Melanie", "f"),
    ("Mia", "f"),
    ("Michael", "m"),
    ("Michelle", "f"),
    ("Miles", "m"),
    ("Molly", "f"),
    ("Monica", "f"),
    ("Morgan", "f"),
    ("Nancy", "f"),
    ("Naomi", "f"),
    ("Natalie", "f"),
    ("Nathan", "m"),
    ("Neil", "m"),
    ("Nicholas", "m"),
    ("Nicole", "f"),
    ("Noah", "m"),
    ("Nora", "f"),
    ("Oliver", "m"),
    ("Olivia", "f"),
    ("Oscar", "m"),
    ("Owen", "m"),
    ("Paige", "f"),
    ("Pamela", "f"),
    ("Patrick", "m"),
    ("Paul", "m"),
    ("Peter", "m"),
    ("Philip", "m"),
    ("Piper", "f"),
    ("Preston", "m"),
    ("Quinn", "f"),
    ("Rachel", "f"),
    ("Randall", "m"),
    ("Raymond", "m"),
    ("Rebecca", "f"),
    ("Richard", "m"),
    ("Riley", "f"),
    ("Robert", "m"),
    ("Robin", "f"),
    ("Roger", "m"),
    ("Rose", "f"),
    ("Ruby", "f"),
    ("Ryan", "m"),
    ("Sabrina", "f"),
    ("Sam", "m"),
    ("Samantha", "f"),
    ("Samuel", "m"),
    ("Sarah", "f"),
    ("Scarlett", "f"),
    ("Sean", "m"),
    ("Sebastian", "m"),
    ("Shannon", "f"),
    ("Sheila", "f"),
    ("Simon", "m"),
    ("Sophia", "f"),
    ("Sophie", "f"),
    ("Stella", "f"),
    ("Stephanie", "f"),
    ("Steven", "m"),
    ("Susan", "f"),
    ("Taylor", "f"),
    ("Teresa", "f"),
    ("Theodore", "m"),
    ("Thomas", "m"),
    ("Tiffany", "f"),
    ("Timothy", "m"),
    ("Travis", "m"),
    ("Trevor", "m"),
    ("Tyler", "m"),
    ("Valerie", "f"),
    ("Vanessa", "f"),
    ("Victoria", "f"),
    ("Vincent", "m"),
    ("Violet", "f"),
    ("Vivian", "f"),
    ("Walter", "m"),
    ("Warren", "m"),
    ("Wendy", "f"),
    ("Wesley", "m"),
    ("William", "m"),
    ("Wyatt", "m"),
    ("Zoe", "f"),
)
FIRST_NAMES = tuple(name for name, _ in FIRST_NAME_DATA)
FIRST_NAME_GENDERS = dict(FIRST_NAME_DATA)
FIRST_NAMES_BY_GENDER = {
    "m": tuple(name for name, gender in FIRST_NAME_DATA if gender == "m"),
    "f": tuple(name for name, gender in FIRST_NAME_DATA if gender == "f"),
}

LAST_NAMES = (
    "Abbott",
    "Adams",
    "Allen",
    "Anderson",
    "Armstrong",
    "Arnold",
    "Atkins",
    "Austin",
    "Bailey",
    "Baker",
    "Ball",
    "Banks",
    "Barber",
    "Barker",
    "Barnes",
    "Barrett",
    "Bates",
    "Becker",
    "Bell",
    "Bennett",
    "Benson",
    "Bishop",
    "Black",
    "Blair",
    "Bowman",
    "Boyd",
    "Bradley",
    "Brewer",
    "Briggs",
    "Brooks",
    "Brown",
    "Bryant",
    "Burke",
    "Burns",
    "Butler",
    "Caldwell",
    "Campbell",
    "Carr",
    "Carson",
    "Carter",
    "Casey",
    "Chambers",
    "Chapman",
    "Chen",
    "Christensen",
    "Clark",
    "Cobb",
    "Cole",
    "Coleman",
    "Collins",
    "Conner",
    "Cook",
    "Cooper",
    "Cox",
    "Craig",
    "Crawford",
    "Cross",
    "Curtis",
    "Daniel",
    "Davis",
    "Day",
    "Diaz",
    "Dixon",
    "Douglas",
    "Duncan",
    "Edwards",
    "Ellis",
    "Evans",
    "Fisher",
    "Fleming",
    "Fletcher",
    "Flores",
    "Foster",
    "Fox",
    "Franklin",
    "Freeman",
    "Garcia",
    "Gardner",
    "Gibson",
    "Gomez",
    "Goodwin",
    "Gordon",
    "Grant",
    "Gray",
    "Green",
    "Griffin",
    "Hale",
    "Hall",
    "Hamilton",
    "Hardy",
    "Harris",
    "Harvey",
    "Hayes",
    "Henderson",
    "Hill",
    "Holland",
    "Holmes",
    "Howard",
    "Howell",
    "Hudson",
    "Hughes",
    "Hunt",
    "Hunter",
    "Jackson",
    "Jacobs",
    "James",
    "Jenkins",
    "Johnson",
    "Jones",
    "Kelly",
    "Kennedy",
    "Khan",
    "King",
    "Knight",
    "Lane",
    "Lawrence",
    "Lee",
    "Leonard",
    "Lewis",
    "Long",
    "Lopez",
    "Lowe",
    "Lucas",
    "Marshall",
    "Martin",
    "Mason",
    "Matthews",
    "May",
    "McCarthy",
    "McDonald",
    "Mendoza",
    "Miller",
    "Mills",
    "Mitchell",
    "Montgomery",
    "Moore",
    "Morris",
    "Morrison",
    "Murphy",
    "Murray",
    "Myers",
    "Nelson",
    "Newton",
    "Nguyen",
    "Nichols",
    "Ortiz",
    "Owens",
    "Page",
    "Palmer",
    "Parker",
    "Patel",
    "Perez",
    "Perkins",
    "Perry",
    "Peters",
    "Peterson",
    "Phillips",
    "Pierce",
    "Porter",
    "Powell",
    "Price",
    "Ramirez",
    "Reed",
    "Reynolds",
    "Richardson",
    "Rivera",
    "Roberts",
    "Robertson",
    "Robinson",
    "Rodriguez",
    "Rogers",
    "Ross",
    "Russell",
    "Sanders",
    "Saunders",
    "Schmidt",
    "Scott",
    "Sharp",
    "Shelton",
    "Simmons",
    "Simpson",
    "Smith",
    "Spencer",
    "Stephens",
    "Stewart",
    "Stone",
    "Sullivan",
    "Taylor",
    "Thomas",
    "Thompson",
    "Tucker",
    "Turner",
    "Vaughn",
    "Walker",
    "Walsh",
    "Walters",
    "Ward",
    "Watson",
    "Weaver",
    "Webb",
    "Wells",
    "West",
    "White",
    "Williams",
    "Wilson",
    "Wood",
    "Woods",
    "Wright",
    "Young",
)


def gender_for_name(name):
    first = name.split(" ", 1)[0]
    return FIRST_NAME_GENDERS.get(first, "m")
